// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkJZRHMSMUz4nRCqtAtXlSVWnl2gHkWjU',
    appId: '1:705282009546:web:8f6bf72508f0a9ae804733',
    messagingSenderId: '705282009546',
    projectId: 'agriculture-fee9c',
    authDomain: 'agriculture-fee9c.firebaseapp.com',
    storageBucket: 'agriculture-fee9c.appspot.com',
    measurementId: 'G-ZJ3N8FYXW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw2yQP21q4lAhsI0U2IzeGd5Ctk_vkc5E',
    appId: '1:705282009546:android:7cdf887b5a600ff1804733',
    messagingSenderId: '705282009546',
    projectId: 'agriculture-fee9c',
    storageBucket: 'agriculture-fee9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzSAcVKgyew4TEQUvRWM0djjLknb3VEQ4',
    appId: '1:705282009546:ios:66356391fb833625804733',
    messagingSenderId: '705282009546',
    projectId: 'agriculture-fee9c',
    storageBucket: 'agriculture-fee9c.appspot.com',
    iosBundleId: 'com.example.agriculture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzSAcVKgyew4TEQUvRWM0djjLknb3VEQ4',
    appId: '1:705282009546:ios:2e0266a259925f13804733',
    messagingSenderId: '705282009546',
    projectId: 'agriculture-fee9c',
    storageBucket: 'agriculture-fee9c.appspot.com',
    iosBundleId: 'com.example.agriculture.RunnerTests',
  );
}
